package com.github.maksimprivalov.subscriptions_telegrambot.javarushclient.dto;

public enum Language {
    UNKNOWN, ENGLISH, GERMAN, SPANISH, HINDI, FRENCH, PORTUGUESE, POLISH, BENGALI, PUNJABI, CHINESE, ITALIAN, INDONESIAN, MARATHI, TAMIL, TELUGU, JAPANESE, KOREAN, URDU, TAIWANESE, NETHERLANDS, RUSSIAN, UKRAINIAN, BULGARIAN, DANISH, HUNGARIAN, JAVANESE, MALAY, NORWEGIAN, ROMANIAN, SWEDISH, THAI, FILIPINO, TURKISH, VIETNAMESE, ARABIC, PERSIAN, HEBREW, SINDHI, AZERBAIJANI, KAZAKH, KYRGYZ, TAJIK, TURKMEN, UZBEK
}
